[package]
name = "rust_authentication_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-redis = "0.13.1"
actix-session = "0.10.1"
actix-web = "4.9.0"
argon2 = "0.5.3"
deadpool-redis = "0.18.0"
dotenv = "0.15.0"
ran = "2.0.1"
rand = "0.8.5"
redis = "0.27.6"
serde = { version = "1.0.216", features = ["derive"] }
sqlx = { version = "0.8.2", features = ["runtime-tokio-rustls", "macros", "postgres", "uuid"] }
time = "0.3.37"
tokio = { version = "1.42.0", features = ["full"] }
uuid = { version = "1.11.0", features = ["v4", "serde"] }
